### **Deep Learning model to predict the propensity of churn for each customer**.

---


### **Steps:**
1. Import Needed Libraries
2. Data Preprocessing
  1. Importing needed dataset
  2. Splitting dependent & independent variable
  3. Missing value treatment
  4. Encoding categorical data
  5. Splitting training and test set
  6. Feature scaling
3. Building ANN Model
  1. Initializing ann
  2. Adding input layer & first hidden layer
  3. Adding second hidden layer
  4. Adding output layer
4. Training ANN Model
  1. Compiling ann
  2. Training ann
5. Testing ANN Model
  1. Predicting test results
  2. Confusion matrix - accuracy

In [1]:
# Here we are going to build an artificial neural network model for churn modelling. 
# whether a customer is going to exit from the bank or not (churn prediction).

In [2]:
# 1. importing needed libraries

import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import confusion_matrix, accuracy_score

In [3]:
# 2. data preprocessing
# 2.1. importing needed dataset

df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
# 2.2. splitting dependent and independent variables

# since we doesn't need RowNumber, CustomerId, Surname we dropped it.
x = df.iloc[:, 3:-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y = df.iloc[:, -1].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [6]:
# 2.3. checking for missing values

df.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 2.4. encoding categorical data
# in our independent variable x Geography & Gender are categorical.

# since gender is binary we are using label encoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
# since geography is not binary we are using one hot encoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
# 2.5. splitting dataset into training and testing

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [10]:
print(x_train)
print()
print(x_test)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [11]:
# 2.6. feature scaling
# it is very important in deep learning. we have to scale all values to same range.

# to avoid information leakage x_train is fitted and transformed
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
print(x_train)
print()
print(x_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [13]:
# 3. building ann model
# 3.1. initializing ann

ann = tf.keras.models.Sequential()

In [14]:
# 3.2. adding input layer and first hidden layer

# there is no rule-of-thumb to fix units. you have add of your own.
# for fully connected neural network we have to use rectifier as activation function
# for non binary classification activation should be 'softmax'
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
# 3.3. adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# 3.4. adding output layer

# since we have one output value to predict; units=1
# for binary output we can use either sigmoid/threshold as activation function
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
# 4. training ann model
# 4.1. compiling ann

# adam optimizer - stochastic gradient descent
# loss - binary_crossentropy for binary output, categorical_crossentropy for non binary output
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
# 4.2. training ann

# batch learning is more efficient in ann
# high no of epochs we can get higher accuracy
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 935us/step - loss: 0.5714 - accuracy: 0.7596
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4676 - accuracy: 0.8043
Epoch 3/100
250/250 [==============================] - 0s 955us/step - loss: 0.4419 - accuracy: 0.8020
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8152
Epoch 5/100
250/250 [==============================] - 0s 933us/step - loss: 0.4081 - accuracy: 0.8263
Epoch 6/100
250/250 [==============================] - 0s 922us/step - loss: 0.3730 - accuracy: 0.8429
Epoch 7/100
250/250 [==============================] - 0s 937us/step - loss: 0.3789 - accuracy: 0.8466
Epoch 8/100
250/250 [==============================] - 0s 988us/step - loss: 0.3694 - accuracy: 0.8458
Epoch 9/100
250/250 [==============================] - 0s 967us/step - loss: 0.3625 - accuracy: 0.8499
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0

In [19]:
# 5. making prediction and evaluating model

# 5.1. predicting test results
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5) # to convert probability value of output to binary
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
# 5.2. cofusion matrix to see model accuracy

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1533   62]
 [ 218  187]]


0.86

In [21]:
# training accuracy - 0.8634; test accuracy - 0.86
# we got similar results from the test and train set, our model is predicting results effectively.
# the end of artificial neural network.